export const GET_DATA_START = 'GET_DATA_START'
export const GET_DATA_ERROR = 'GET_DATA_ERROR'
export const GET_DATA_END   = 'GET_DATA_END'

export const DELETE_DATA_START = 'DELETE_DATA_START'
export const DELETE_DATA_ERROR = 'DELETE_DATA_ERROR'
export const DELETE_DATA_END   = 'DELETE_DATA_END'

export const EDIT_DATA_START = 'EDIT_DATA_START'
export const EDIT_DATA_ERROR = 'EDIT_DATA_ERROR'
export const EDIT_DATA_END   = 'EDIT_DATA_END'

export const CREAT_DATA_START = 'CREAT_DATA_START'
export const CREAT_DATA_ERROR = 'CREAT_DATA_ERROR'
export const CREAT_DATA_END   = 'CREAT_DATA_END'